version: 2.0
jobs:
  build:
    working_directory: ~/reactDocker
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run: npm install
      - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
heroku_deploy:
    jobs:
      - heroku/deploy-via-git         
    orbs:
     sonarcloud: sonarsource/sonarcloud@1.0.1
    workflows:
      main:
        jobs:
          - build:
              context: SonarCloud
     