version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: /home/ubuntu/cci-demo-react
    steps:
      - checkout
    
      - run: mkdir -p /home/ubuntu/cci-demo-react/artifacts
        # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm test
      - store_artifacts:
          path: /home/ubuntu/cci-demo-react/artifacts    

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main