version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo
      - run:
          name: build 
          command: npm run build 
      - store_artifacts:
          path: build  
    

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud  
  