version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo
      - run:
          name: build 
          command: npm run build 
      - store_artifacts:
          path: build  
      - deploy:
         name: aws
         command: ssh -i "~/repo/firstec.pem" ubuntu@ec2-13-235-45-232.ap-south-1.compute.amazonaws.com "cd ~/profile-store; git pull; sudo npm install; sudo systemctl restart nginx"    

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main